### ISSUE TITLE
.pcon 不正确的返回异常

### ISSUE THREAD

**Issue by Eiriksgata** [Eiriksgata/mirai-rulateday-dice#102]
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.dice.message.handle.InstructHandle.trackInstructCases(InstructHandle.java:75)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.dice.message.handle.InstructHandle.instructCheck(InstructHandle.java:37)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.DiceMessageEventHandle.groupMessageHandle(DiceMessageEventHandle.java:153)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.DiceMessageEventHandle.onGroupMessage(DiceMessageEventHandle.java:108)
	at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error committing transaction.  Cause: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
### Cause: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:226)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:217)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.instruction.ConfigController.privateChatOn(ConfigController.java:22)
	... 22 more
Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.sqlite.core.DB.newSQLException(DB.java:1012)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.sqlite.core.DB.newSQLException(DB.java:1024)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.sqlite.core.DB.throwex(DB.java:989)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.sqlite.core.DB.exec(DB.java:178)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:412)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.apache.ibatis.datasource.pooled.PooledConnection.invoke(PooledConnection.java:255)
	at jdk.proxy4/jdk.proxy4.$Proxy39.commit(Unknown Source)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.apache.ibatis.transaction.jdbc.JdbcTransaction.commit(JdbcTransaction.java:72)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.apache.ibatis.executor.BaseExecutor.commit(BaseExecutor.java:244)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.apache.ibatis.executor.CachingExecutor.commit(CachingExecutor.java:119)
	at rulateday-server-pro-0.4.4-SNAPSHOT-jar-with-dependencies.jar//org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:223)
	... 24 more

```

**Comment by Eiriksgata** [comment]
数据库文件是被Locked 的，应当返回给用户 ，让其重启。

**Comment by Eiriksgata** [comment]
这个异常错误跟指令没有关系，只是数据库表被锁。
