### ISSUE TITLE
.trpg-option-0 不正确的异常返回

### ISSUE THREAD

**Issue by Eiriksgata** [Eiriksgata/mirai-rulateday-dice#103]
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.dice.message.handle.InstructHandle.trackInstructCases(InstructHandle.java:75)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.dice.message.handle.InstructHandle.instructCheck(InstructHandle.java:37)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.DiceMessageEventHandle.groupMessageHandle(DiceMessageEventHandle.java:158)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.DiceMessageEventHandle.onGroupMessage(DiceMessageEventHandle.java:113)
	at jdk.internal.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.NullPointerException
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.trpggame.RoleDataHandler.update(RoleDataHandler.java:12)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.trpggame.TrpgGameServiceImpl.lambda$roleDataUpdate$0(TrpgGameServiceImpl.java:164)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.trpggame.TrpgGameServiceImpl.roleDataUpdate(TrpgGameServiceImpl.java:160)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.trpggame.TrpgGameServiceImpl.optionSelect(TrpgGameServiceImpl.java:142)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.instruction.GalGameController$2.group(GalGameController.java:78)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.event.EventUtils.eventCallback(EventUtils.java:17)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.instruction.GalGameController.trpgOptionSelect(GalGameController.java:75)
	... 22 more


```

**Comment by Eiriksgata** [comment]
依旧是tprg 模组的json文件 判断的属性不存在 https://github.com/Eiriksgata/mirai-rulateday-dice/blob/996d5ff34835c4035d9dc45cf10b481332117306/rulateday-server/src/main/java/indi/eiriksgata/rulateday/trpggame/RoleDataHandler.java#L12
