### ISSUE TITLE
.trpg-reload爱索尔德.json 错误的返回异常

### ISSUE THREAD

**Issue by Eiriksgata** [Eiriksgata/mirai-rulateday-dice#104]
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.dice.message.handle.InstructHandle.trackInstructCases(InstructHandle.java:75)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.dice.message.handle.InstructHandle.instructCheck(InstructHandle.java:37)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.DiceMessageEventHandle.groupMessageHandle(DiceMessageEventHandle.java:158)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.DiceMessageEventHandle.onGroupMessage(DiceMessageEventHandle.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.NullPointerException
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.trpggame.TrpgGameServiceImpl.loadEventText(TrpgGameServiceImpl.java:82)
	at rulateday-server-pro-0.4.5-SNAPSHOT-jar-with-dependencies.jar//indi.eiriksgata.rulateday.instruction.GalGameController.trpgGameLoad(GalGameController.java:58)
	... 23 more


```

**Comment by Eiriksgata** [comment]
这个异常导致的代码行数为[ TrpgGameServiceImpl.java:82](https://github.com/Eiriksgata/mirai-rulateday-dice/blob/996d5ff34835c4035d9dc45cf10b481332117306/rulateday-server/src/main/java/indi/eiriksgata/rulateday/trpggame/TrpgGameServiceImpl.java#L82)

是由于trpg的模组json文件 中的option - x - count 不存在参数
