### ISSUE TITLE
由指令"。。。"返回的异常情况

### ISSUE THREAD

**Issue by Eiriksgata** [Eiriksgata/mirai-rulateday-dice#105]
```
org.reflections.ReflectionsException: Scanner TypeAnnotationsScanner was not configured
	at org.reflections.Store.get(Store.java:39)
	at org.reflections.Store.get(Store.java:61)
	at org.reflections.Store.get(Store.java:46)
	at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:429)
	at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:416)
	at indi.eiriksgata.dice.message.handle.InstructHandle.trackInstructCases(InstructHandle.java:43)
	at indi.eiriksgata.dice.message.handle.InstructHandle.instructCheck(InstructHandle.java:37)
	at indi.eiriksgata.rulateday.DiceMessageEventHandle.groupMessageHandle(DiceMessageEventHandle.java:153)
	at indi.eiriksgata.rulateday.DiceMessageEventHandle.onGroupMessage(DiceMessageEventHandle.java:108)
	at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by Eiriksgata** [comment]
这个异常上报应该是由其他人 拉取开发后导致的异常返回，初步推测应该是没有配置好trpg-java-dice  项目配置文件：trpg-dice-config.properties
