### ISSUE TITLE
.atklist 指令异常

### ISSUE THREAD

**Issue by Eiriksgata** [Eiriksgata/mirai-rulateday-dice#88]
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at indi.eiriksgata.dice.message.handle.InstructHandle.trackInstructCases(InstructHandle.java:75)
	at indi.eiriksgata.dice.message.handle.InstructHandle.instructCheck(InstructHandle.java:37)
	at indi.eiriksgata.rulateday.DiceMessageEventHandle.groupMessageHandle(DiceMessageEventHandle.java:153)
	at indi.eiriksgata.rulateday.DiceMessageEventHandle.onGroupMessage(DiceMessageEventHandle.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NullPointerException
	at java.base/java.text.MessageFormat.applyPattern(MessageFormat.java:448)
	at java.base/java.text.MessageFormat.<init>(MessageFormat.java:370)
	at java.base/java.text.MessageFormat.format(MessageFormat.java:859)
	at indi.eiriksgata.dice.reply.CustomText.getText(CustomText.java:66)
	at indi.eiriksgata.rulateday.service.impl.UserInitiativeServerImpl.showInitiativeList(UserInitiativeServerImpl.java:70)
	at indi.eiriksgata.rulateday.instruction.InitiativeController$1.group(InitiativeController.java:35)
	at indi.eiriksgata.rulateday.event.EventUtils.eventCallback(EventUtils.java:17)
	at indi.eiriksgata.rulateday.instruction.InitiativeController.getAtkList(InitiativeController.java:31)
	... 23 more

```

**Comment by Eiriksgata** [comment]
主要导致原因是代码中的文本里面没有修改完，使用了`dice.xxxxxx`
